### ISSUE TITLE
Fatal error: "Class 'Symfony\Component\Ldap\Ldap' not found"

### ISSUE THREAD

**Issue by sfuerte** [shanept/mediawiki-LdapAuth#3]
Getting the following trace:
`[38f4ffaec5dea7a5eb1c0904] /index.php?title=Special:UserLogin&returnto=Special:Version Error from line 388 of /var/www/mediawiki/extensions/LdapAuth/src/Auth/PrimaryAuthenticationProvider.php: Class 'Symfony\Component\Ldap\Ldap' not found

Backtrace:
```
#0 /var/www/mediawiki/extensions/LdapAuth/src/Auth/PrimaryAuthenticationProvider.php(110): Shanept\LdapAuth\Auth\PrimaryAuthenticationProvider->connect(Shanept\LdapAuth\Auth\LdapAuthenticationRequest)
#1 /var/www/mediawiki/extensions/LdapAuth/src/Auth/PrimaryAuthenticationProvider.php(88): Shanept\LdapAuth\Auth\PrimaryAuthenticationProvider->beginPrimaryLdapAuthentication(Shanept\LdapAuth\Auth\LdapAuthenticationRequest)
#2 /var/www/mediawiki/includes/auth/AuthManager.php(453): Shanept\LdapAuth\Auth\PrimaryAuthenticationProvider->beginPrimaryAuthentication(array)
#3 /var/www/mediawiki/includes/auth/AuthManager.php(383): MediaWiki\Auth\AuthManager->continueAuthentication(array)
#4 /var/www/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(353): MediaWiki\Auth\AuthManager->beginAuthentication(array, string)
#5 /var/www/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(482): AuthManagerSpecialPage->performAuthenticationStep(string, array)
#6 /var/www/mediawiki/includes/htmlform/HTMLForm.php(660): AuthManagerSpecialPage->handleFormSubmit(array, VFormHTMLForm)
#7 /var/www/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(416): HTMLForm->trySubmit()
#8 /var/www/mediawiki/includes/specialpage/LoginSignupSpecialPage.php(316): AuthManagerSpecialPage->trySubmit()
#9 /var/www/mediawiki/includes/specialpage/SpecialPage.php(522): LoginSignupSpecialPage->execute(NULL)
#10 /var/www/mediawiki/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#11 /var/www/mediawiki/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#12 /var/www/mediawiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#13 /var/www/mediawiki/includes/MediaWiki.php(524): MediaWiki->main()
#14 /var/www/mediawiki/index.php(42): MediaWiki->run()
#15 {main}
```

`composer install` has been done:
```
mediawiki# ls -l extensions/LdapAuth/vendor/
total 60K
-rw-r--r-- 1 www-data root  178 Nov 22 15:52 autoload.php
drwxr-xr-x 2 www-data root 4096 Nov 22 15:49 bin
drwxr-xr-x 5 www-data root 4096 Nov 22 15:49 composer
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 felixfbecker
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 jakub-onderka
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 mediawiki
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 microsoft
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 netresearch
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 phan
drwxr-xr-x 5 www-data root 4096 Nov 22 15:49 phpdocumentor
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 psr
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 sabre
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 squizlabs
drwxr-xr-x 6 www-data root 4096 Nov 22 15:49 symfony
drwxr-xr-x 3 www-data root 4096 Nov 22 15:49 webmozart
```

```
/mediawiki# ls -l extensions/LdapAuth/vendor/symfony/
total 16K
drwxr-xr-x 19 www-data root 4096 Nov 22 15:49 console
drwxr-xr-x  5 www-data root 4096 Nov 22 15:49 ldap
drwxr-xr-x  5 www-data root 4096 Nov 22 15:49 options-resolver
drwxr-xr-x  3 www-data root 4096 Nov 22 15:49 polyfill-mbstring
```

Settings as follows:
```
mediawiki# grep LdapAuth LocalSettings.php
wfLoadExtension( 'LdapAuth' );
$wgLdapAuthDomainNames = 'DOMAIN';
$wgLdapAuthServers = 'SERVER';
$wgLdapAuthBindDN = 'CN=..';
$wgLdapAuthBindPass = '..';
$wgLdapAuthBaseDN = 'CN=Users,DC=DOMAIN';
$wgLdapAuthIsActiveDirectory = true;
```

PHP LDAP has been installed as well:
```
@wiki:/var/www/mediawiki# dpkg -l | grep php7.2 | awk '{ print $2 }'
libapache2-mod-php7.2
php7.2-cli
php7.2-common
php7.2-curl
php7.2-gd
php7.2-json
php7.2-ldap
php7.2-mbstring
php7.2-mysql
php7.2-opcache
php7.2-phpdbg
php7.2-readline
php7.2-xml
```

**Comment by shanept** [comment]
Hi @sfuerte 

Please run `composer install` in the wiki base, rather than the plugin's directory - and then confirm if this solves your issue?
You shouldn't need a vendor directory in your LdapAuth folder at all.

**Comment by sfuerte** [comment]
@shanept, I did run `composer install` when installing the extension. 
`composer.json` does contain the extra section:
```
        "extra": {
                "merge-plugin": {
                        "include": [
                                "composer.local.json"
                        ],
                        "merge-dev": false
                }
        }
```

While I did run `php maintenance/update.php` before, just done it again:
```
@wiki:mediawiki> sudo php maintenance/update.php
MediaWiki 1.31.1 Updater

Your composer.lock file is up to date with current dependencies!
Going to run database updates for my_wiki
...
```

Running `composer install` in the Wiki base did put some new dependencies, but none of them are LDAP related. 

The problem still persists.

**Comment by Eikir** [comment]
I do have the same issue as @sfuerte.
Furthemore [this page](https://www.mediawiki.org/wiki/Extension:LdapAuth) said: 
> Run Composer to install PHP dependencies, by issuing composer install **in the extension directory**.

**Comment by ljonka** [comment]
i fixed the same error by running;
`composer require symfony/ldap` 
in mediawiki's base directory.

**Comment by shanept** [comment]
This is bizarre - the composer require shouldn't be required, as it is required for the plugin. This dependency management should bubble up to mediawiki as part of the composer-merge plugin.
Can you investigate your composer.json and composer.local.json, and verify them against the original source?

**Comment by yesi** [comment]
HI,
The same error from my fresh install.
Since the server has not access to internet ; what is the best way toe resolve this.
I'm coming with the TLS of mediawiki 1.31.1 and the ldapauth, the last one.

[mediawiki.log](https://github.com/shanept/mediawiki-LdapAuth/files/2860962/mediawiki.log)

**Comment by ljonka** [comment]
i think that was my fault, i am not using composer merge plugin. @shanept this should not happen if installed with help of the merge plugin. 
@yesi  i would recommend you to prepare the plugin local including composer libs and to export the plugin including composer libs. (https://getcomposer.org/doc/03-cli.md#archive)

**Comment by yesi** [comment]
Hi @ljonka 
Sorry, i don't get it...

Should i clone the directory mediawiki to a station with internet access ? Then run this below command ?
In which directory should i be before run it ? And what is the **given version** ?

>  php composer.phar archive vendor/package 2.0.21 --format=zip

**Comment by ljonka** [comment]
yes, you can try to prepare the archive on a machine with internet access:
**Clone extension**
`git clone https://github.com/shanept/mediawiki-LdapAuth.git `
**Enter directory**
`cd mediawiki-LdapAuth`
**Install libraries / dependencies**
`composer install`
**Export whole directory including dependencies**
`composer archive --format=zip --dir=../ --file=mediawiki-LdapAuth`

**Comment by yesi** [comment]
@shanept 
the contect of composer.json :
https://github.com/shanept/mediawiki-LdapAuth/issues/3#issuecomment-442222218

The composer.local.json , i created
{ "extra": {
"merge-plugin": {
"include" : [
"extensions/LdapAuth/composer.json"
]
}
}
}
@ljonka 
I will give a try later. Thanks

**Comment by ljonka** [comment]
@yesi  dont forget to include the vendor dir in composer.json as mentioned in https://github.com/composer/composer/issues/6620#issuecomment-324123913

**Comment by yesi** [comment]
@ljonka 
The file composer.json modified 
```
{
    "name": "shanept/ldap-auth",
    "description": "New LdapAuthentication provider plugin for mediawiki",
    "type": "project",
    "require": {
        "symfony/ldap": "^4.1"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Shane Thompson",
            "email": "me@shane.pt"
        }
    ],
    "require-dev": {
        "jakub-onderka/php-parallel-lint": "^1.0",
        "mediawiki/mediawiki-codesniffer": "^22.0",
        "phan/phan": "^1.1"
    },
    "scripts": {
        "test": [
            "parallel-lint . --exclude vendor",
            "phpcs -p -s"
        ]
    }
    "archive": {
        "exclude": [
            ".*",
            "!.gitignore",
            "node_modules/",
            "vendor/",
            "www/",
            "composer/",
            "*.yml"
        ]
    }
}

```

**Comment by ljonka** [comment]
"!vendor/", 
To include vendor dir. The rest can be ignored/removed (as far as I see)

**Comment by yesi** [comment]
After modifications and following above recommandations, i get the same error message from debug mode.
`Error from line 388 of /var/www/mediawiki/extensions/LdapAuth/src/Auth/PrimaryAuthenticationProvider.php: Class 'Symfony\Component\Ldap\Ldap' not found`

**Comment by yesi** [comment]
`ls symfony/`

> console  contracts  ldap  options-resolver  polyfill-ctype  polyfill-mbstring

There is no directory : **Symfony/Component**

**Comment by ljonka** [comment]
I think the merge-plugin ignore the files of extension/LdapAuth/vendor/symphony/ldap you can try to tweak the merge-plugin usage in /composer.json to activate autoloading of extensions/LdapAuth/vendor/autoload.php
In general mediawiki does not like vendor libs in extension folders. It is better to include composer.json files from each extension in composer.local.json and "composer install" required libs into base vendor dir.

**Comment by yesi** [comment]
1) into which file below :   
- mediawiki/composer.json --> never modified
- mediawiki/composer.local.json  --> created
`{ "extra": {"merge-plugin": {"include" : ["extensions/LdapAuth/composer.json"]}}}`
- mediawiki/extension/LdapAuth/composer.json  --> modified
```
{
    "name": "shanept/ldap-auth",
    "description": "New LdapAuthentication provider plugin for mediawiki",
    "type": "project",
    "require": {
        "symfony/ldap": "^4.1"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Shane Thompson",
            "email": "me@shane.pt"
        }
    ],
    "require-dev": {
        "jakub-onderka/php-parallel-lint": "^1.0",
        "mediawiki/mediawiki-codesniffer": "^22.0",
        "phan/phan": "^1.1"
    },
    "scripts": {
        "test": [
            "parallel-lint . --exclude vendor",
            "phpcs -p -s"
        ]
    },
    "archive": {
        "exclude": [
            ".*",
            "!.gitignore",
            "node_modules/",
            "!vendor/",
            "www/",
            "composer/",
            "*.yml"
        ]
    }
}
```

2) what is the syntax, please ?

**Comment by DevSysEngineer** [comment]
It's important to run follow this steps: https://www.mediawiki.org/wiki/Composer before you are installing this extension.

```
Using composer-merge-plugin
MediaWiki core "owns" $IP/composer.json and will change the contents of that file in both tarball and Git managed updates. In order to allow local installs to use Composer to load optional libraries and/or manage extensions with Composer, a special plugin for Composer named composer-merge-plugin was developed.[2] This plugin and the MediaWiki core composer.json configuration allow a local deployment to add required extensions and libraries to a file composer.local.json inside the root MediaWiki directory.

composer.local.json can also be used to install Composer managed libraries that are needed by extensions that are not installed using Composer themselves. This is only needed when the extensions are not installed from tarballs generated by Extension Distributor.

To enable Composer to discover and process the composer.json files that may be included in any and all of your locally installed extensions, add something like this to $IP/composer.local.json:

{
    "extra": {
        "merge-plugin": {
            "include": [
                "extensions/*/composer.json",
                "skins/*/composer.json"
            ]
        }
    }
}
```

Run `composer update` and `composer install` in de root dir of your wiki location.
